<?php

return [
    'disk' => env('MEDIA_DISK', 'public'),
    'driver' => env('MEDIA_DRIVER', env('MEDIA_DISK', 'public')),
    'private_disk' => env('MEDIA_PRIVATE_DISK', 'local'),
    'private_access_mode' => env('MEDIA_PRIVATE_ACCESS_MODE', 'auth'),
    'signed_url_ttl_minutes' => env('MEDIA_SIGNED_URL_TTL_MINUTES', 30),
    'only_view_own_media' => env('MEDIA_ONLY_VIEW_OWN_MEDIA', false),
    'default_upload_folder' => env('MEDIA_DEFAULT_UPLOAD_FOLDER', ''),
    'default_upload_url' => env('MEDIA_DEFAULT_UPLOAD_URL'),
    'use_original_name_for_file_path' => env('MEDIA_USE_ORIGINAL_NAME_FOR_FILE_PATH', false),
    'convert_file_name_to_uuid' => env('MEDIA_CONVERT_FILE_NAME_TO_UUID', false),
    'keep_original_file_size_and_quality' => env('MEDIA_KEEP_ORIGINAL_FILE_SIZE_AND_QUALITY', false),
    'turn_off_automatic_url_translation_into_latin' => env('MEDIA_TURN_OFF_AUTOMATIC_URL_TRANSLATION_INTO_LATIN', false),
    'convert_image_to_webp' => env('MEDIA_CONVERT_IMAGE_TO_WEBP', false),
    'reduce_large_image_size' => env('MEDIA_REDUCE_LARGE_IMAGE_SIZE', false),
    'image_max_width' => env('MEDIA_IMAGE_MAX_WIDTH'),
    'image_max_height' => env('MEDIA_IMAGE_MAX_HEIGHT'),
    'customize_upload_path' => env('MEDIA_CUSTOMIZE_UPLOAD_PATH', false),
    'upload_path' => env('MEDIA_UPLOAD_PATH', 'storage'),
    'generate_thumbnails_enabled' => env('MEDIA_GENERATE_THUMBNAILS_ENABLED', false),
    'generate_thumbnails_chunk_limit' => env('MEDIA_GENERATE_THUMBNAILS_CHUNK_LIMIT', 50),
    'queue_thumbnails' => env('MEDIA_QUEUE_THUMBNAILS', false),
    'enable_thumbnail_sizes' => env('MEDIA_ENABLE_THUMBNAIL_SIZES', true),
    'thumbnail_crop_position' => env('MEDIA_THUMBNAIL_CROP_POSITION', 'center'),
    'image_processing_library' => env('MEDIA_IMAGE_PROCESSING_LIBRARY', 'gd'),
    'sizes' => [
        'thumb' => '150x150',
    ],
    'allowed_mime_types' => env(
        'MEDIA_ALLOWED_MIME_TYPES',
        'jpg,jpeg,png,gif,txt,docx,zip,mp3,bmp,csv,xls,xlsx,ppt,pptx,pdf,mp4,m4v,doc,mpga,wav,webp,webm,mov,jfif,avif,rar,x-rar'
    ),
    'allowed_admin_to_upload_any_file_types' => env('MEDIA_ALLOWED_ADMIN_TO_UPLOAD_ANY_FILE_TYPES', false),
    'mime_types' => [
        'image' => [
            'image/png',
            'image/jpeg',
            'image/gif',
            'image/bmp',
            'image/svg+xml',
            'image/webp',
            'image/avif',
        ],
        'video' => [
            'video/mp4',
            'video/m4v',
            'video/mov',
            'video/quicktime',
        ],
        'document' => [
            'application/pdf',
            'application/vnd.ms-excel',
            'application/excel',
            'application/x-excel',
            'application/x-msexcel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'text/plain',
            'application/msword',
            'text/csv',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.ms-powerpoint',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'zip' => [
            'application/zip',
            'application/x-zip-compressed',
            'application/x-compressed',
            'multipart/x-zip',
            'multipart/x-rar',
            'application/x-rar-compressed',
            'application/vnd.rar',
        ],
        'audio' => [
            'audio/mpeg',
            'audio/mp3',
            'audio/wav',
        ],
    ],
    'default_placeholder_image' => env('MEDIA_DEFAULT_PLACEHOLDER_IMAGE'),
    'sidebar_display' => env('MEDIA_SIDEBAR_DISPLAY', 'horizontal'),
    'watermark' => [
        'enabled' => env('MEDIA_WATERMARK_ENABLED', 0),
        'source' => env('MEDIA_WATERMARK_SOURCE'),
        'size' => env('MEDIA_WATERMARK_SIZE', 10),
        'opacity' => env('MEDIA_WATERMARK_OPACITY', 70),
        'position' => env('MEDIA_WATERMARK_POSITION', 'bottom-right'),
        'x' => env('MEDIA_WATERMARK_POSITION_X', 10),
        'y' => env('MEDIA_WATERMARK_POSITION_Y', 10),
    ],
    'custom_s3_path' => env('MEDIA_S3_PATH', ''),
    'chunk' => [
        'enabled' => env('MEDIA_CHUNK_ENABLED', false),
        'chunk_size' => env('MEDIA_CHUNK_SIZE', 1024 * 1024),
        'max_file_size' => env('MEDIA_MAX_FILE_SIZE', 50 * 1024 * 1024),
        'storage' => [
            'chunks' => 'chunks',
            'disk' => 'local',
        ],
        'clear' => [
            'timestamp' => '-3 HOURS',
            'schedule' => [
                'enabled' => true,
                'cron' => '25 * * * *',
            ],
        ],
    ],
    'cache' => [
        'user_item_ttl_seconds' => env('MEDIA_USER_ITEM_CACHE_TTL_SECONDS', 300),
    ],
    'throttle' => [
        'show_file' => env('MEDIA_SHOW_FILE_THROTTLE', '120,1'),
    ],
    'preview' => [
        'document' => [
            'enabled' => env('MEDIA_DOCUMENT_PREVIEW_ENABLED', true),
            'providers' => [
                'google' => 'https://docs.google.com/gview?embedded=true&url={url}',
                'microsoft' => 'https://view.officeapps.live.com/op/view.aspx?src={url}',
            ],
            'default' => env('MEDIA_DOCUMENT_PREVIEW_PROVIDER', 'microsoft'),
            'type' => env('MEDIA_DOCUMENT_PREVIEW_TYPE', 'iframe'),
            'mime_types' => [
                'application/pdf',
                'application/vnd.ms-excel',
                'application/excel',
                'application/x-excel',
                'application/x-msexcel',
                'application/msword',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'application/vnd.ms-powerpoint',
                'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            ],
        ],
    ],
    'folder_colors' => [
        '#3498db',
        '#2ecc71',
        '#e74c3c',
        '#f39c12',
        '#9b59b6',
        '#1abc9c',
        '#34495e',
        '#e67e22',
        '#27ae60',
        '#c0392b',
    ],
    'use_storage_symlink' => env('MEDIA_USE_STORAGE_SYMLINK', false),
    'settings_defaults' => [
        'media_driver' => env('MEDIA_DRIVER', env('MEDIA_DISK', 'public')),
        'media_aws_access_key_id' => env('MEDIA_AWS_ACCESS_KEY_ID', env('AWS_ACCESS_KEY_ID')),
        'media_aws_secret_key' => env('MEDIA_AWS_SECRET_KEY', env('AWS_SECRET_ACCESS_KEY')),
        'media_aws_default_region' => env('MEDIA_AWS_DEFAULT_REGION', env('AWS_DEFAULT_REGION')),
        'media_aws_bucket' => env('MEDIA_AWS_BUCKET', env('AWS_BUCKET')),
        'media_aws_url' => env('MEDIA_AWS_URL', env('AWS_URL')),
        'media_aws_endpoint' => env('MEDIA_AWS_ENDPOINT', env('AWS_ENDPOINT')),
        'media_aws_use_path_style_endpoint' => env('MEDIA_AWS_USE_PATH_STYLE_ENDPOINT', env('AWS_USE_PATH_STYLE_ENDPOINT', false)),
        'media_r2_access_key_id' => env('MEDIA_R2_ACCESS_KEY_ID'),
        'media_r2_secret_key' => env('MEDIA_R2_SECRET_KEY'),
        'media_r2_bucket' => env('MEDIA_R2_BUCKET'),
        'media_r2_url' => env('MEDIA_R2_URL'),
        'media_r2_endpoint' => env('MEDIA_R2_ENDPOINT'),
        'media_r2_use_path_style_endpoint' => env('MEDIA_R2_USE_PATH_STYLE_ENDPOINT', true),
        'media_do_spaces_access_key_id' => env('MEDIA_DO_SPACES_ACCESS_KEY_ID'),
        'media_do_spaces_secret_key' => env('MEDIA_DO_SPACES_SECRET_KEY'),
        'media_do_spaces_default_region' => env('MEDIA_DO_SPACES_DEFAULT_REGION'),
        'media_do_spaces_bucket' => env('MEDIA_DO_SPACES_BUCKET'),
        'media_do_spaces_endpoint' => env('MEDIA_DO_SPACES_ENDPOINT'),
        'media_do_spaces_cdn_enabled' => env('MEDIA_DO_SPACES_CDN_ENABLED', false),
        'media_do_spaces_cdn_custom_domain' => env('MEDIA_DO_SPACES_CDN_CUSTOM_DOMAIN'),
        'media_do_spaces_use_path_style_endpoint' => env('MEDIA_DO_SPACES_USE_PATH_STYLE_ENDPOINT', false),
        'media_wasabi_access_key_id' => env('MEDIA_WASABI_ACCESS_KEY_ID'),
        'media_wasabi_secret_key' => env('MEDIA_WASABI_SECRET_KEY'),
        'media_wasabi_default_region' => env('MEDIA_WASABI_DEFAULT_REGION'),
        'media_wasabi_bucket' => env('MEDIA_WASABI_BUCKET'),
        'media_wasabi_root' => env('MEDIA_WASABI_ROOT', '/'),
        'media_bunnycdn_zone' => env('MEDIA_BUNNYCDN_ZONE'),
        'media_bunnycdn_hostname' => env('MEDIA_BUNNYCDN_HOSTNAME'),
        'media_bunnycdn_key' => env('MEDIA_BUNNYCDN_KEY'),
        'media_bunnycdn_region' => env('MEDIA_BUNNYCDN_REGION'),
        'media_backblaze_access_key_id' => env('MEDIA_BACKBLAZE_ACCESS_KEY_ID'),
        'media_backblaze_secret_key' => env('MEDIA_BACKBLAZE_SECRET_KEY'),
        'media_backblaze_default_region' => env('MEDIA_BACKBLAZE_DEFAULT_REGION'),
        'media_backblaze_bucket' => env('MEDIA_BACKBLAZE_BUCKET'),
        'media_backblaze_endpoint' => env('MEDIA_BACKBLAZE_ENDPOINT'),
        'media_backblaze_use_path_style_endpoint' => env('MEDIA_BACKBLAZE_USE_PATH_STYLE_ENDPOINT', false),
        'media_backblaze_cdn_enabled' => env('MEDIA_BACKBLAZE_CDN_ENABLED', false),
        'media_backblaze_cdn_custom_domain' => env('MEDIA_BACKBLAZE_CDN_CUSTOM_DOMAIN'),
        'media_use_original_name_for_file_path' => env('MEDIA_USE_ORIGINAL_NAME_FOR_FILE_PATH', false),
        'media_convert_file_name_to_uuid' => env('MEDIA_CONVERT_FILE_NAME_TO_UUID', false),
        'media_keep_original_file_size_and_quality' => env('MEDIA_KEEP_ORIGINAL_FILE_SIZE_AND_QUALITY', false),
        'media_turn_off_automatic_url_translation_into_latin' => env('MEDIA_TURN_OFF_AUTOMATIC_URL_TRANSLATION_INTO_LATIN', false),
        'user_can_only_view_own_media' => env('MEDIA_ONLY_VIEW_OWN_MEDIA', false),
        'media_convert_image_to_webp' => env('MEDIA_CONVERT_IMAGE_TO_WEBP', false),
        'media_default_placeholder_image' => env('MEDIA_DEFAULT_PLACEHOLDER_IMAGE'),
        'media_reduce_large_image_size' => env('MEDIA_REDUCE_LARGE_IMAGE_SIZE', false),
        'media_image_max_width' => env('MEDIA_IMAGE_MAX_WIDTH'),
        'media_image_max_height' => env('MEDIA_IMAGE_MAX_HEIGHT'),
        'media_customize_upload_path' => env('MEDIA_CUSTOMIZE_UPLOAD_PATH', false),
        'media_upload_path' => env('MEDIA_UPLOAD_PATH', 'storage'),
        'media_watermark_enabled' => env('MEDIA_WATERMARK_ENABLED', 0),
        'media_folders_can_add_watermark' => [],
        'media_watermark_source' => env('MEDIA_WATERMARK_SOURCE'),
        'media_watermark_size' => env('MEDIA_WATERMARK_SIZE', 10),
        'media_watermark_opacity' => env('MEDIA_WATERMARK_OPACITY', 70),
        'media_watermark_position' => env('MEDIA_WATERMARK_POSITION', 'bottom-right'),
        'media_watermark_position_x' => env('MEDIA_WATERMARK_POSITION_X', 10),
        'media_watermark_position_y' => env('MEDIA_WATERMARK_POSITION_Y', 10),
        'media_image_processing_library' => env('MEDIA_IMAGE_PROCESSING_LIBRARY', 'gd'),
        'media_enable_thumbnail_sizes' => env('MEDIA_ENABLE_THUMBNAIL_SIZES', true),
        'media_thumbnail_crop_position' => env('MEDIA_THUMBNAIL_CROP_POSITION', 'center'),
        'media_chunk_enabled' => env('MEDIA_CHUNK_ENABLED', false),
        'media_chunk_size' => env('MEDIA_CHUNK_SIZE', 1024 * 1024),
        'media_max_file_size' => env('MEDIA_MAX_FILE_SIZE', 50 * 1024 * 1024),
        'media_s3_path' => env('MEDIA_S3_PATH', ''),
    ],
];
