<?php

return [
    'flags' => [
        'ad' => 'Andorra',
        'ae' => 'United Arab Emirates',
        'af' => 'Afghanistan',
        'ag' => 'Antigua and Barbuda',
        'ai' => 'Anguilla',
        'al' => 'Albania',
        'am' => 'Armenia',
        'ao' => 'Angola',
        'ar' => 'Argentina',
        'as' => 'American Samoa',
        'at' => 'Austria',
        'au' => 'Australia',
        'aw' => 'Aruba',
        'ax' => 'Åland Islands',
        'az' => 'Azerbaijan',
        'ba' => 'Bosnia and Herzegovina',
        'bb' => 'Barbados',
        'bd' => 'Bangladesh',
        'be' => 'Belgium',
        'bf' => 'Burkina Faso',
        'bg' => 'Bulgaria',
        'bh' => 'Bahrain',
        'bi' => 'Burundi',
        'bj' => 'Benin',
        'bm' => 'Bermuda',
        'bn' => 'Brunei',
        'bo' => 'Bolivia',
        'br' => 'Brazil',
        'bs' => 'Bahamas',
        'bt' => 'Bhutan',
        'bw' => 'Botswana',
        'by' => 'Belarus',
        'bz' => 'Belize',
        'ca' => 'Canada',
        'ca_ES' => 'Catalonia',
        'cc' => 'Cocos',
        'cd' => 'Democratic Republic of the Congo',
        'cf' => 'Central African Republic',
        'cg' => 'Congo',
        'ch' => 'Switzerland',
        'ci' => 'Ivory Coast',
        'ck' => 'Cook Islands',
        'cl' => 'Chile',
        'cm' => 'Cameroon',
        'cn' => 'China',
        'co' => 'Colombia',
        'cr' => 'Costa Rica',
        'cu' => 'Cuba',
        'cv' => 'Cape Verde',
        'cx' => 'Christmas Island',
        'cy' => 'Cyprus',
        'cz' => 'Czech Republic',
        'de' => 'Germany',
        'dj' => 'Djibouti',
        'dk' => 'Denmark',
        'dm' => 'Dominica',
        'do' => 'Dominican Republic',
        'dz' => 'Algeria',
        'ec' => 'Ecuador',
        'ee' => 'Estonia',
        'eg' => 'Egypt',
        'eh' => 'Western Sahara',
        'gb-eng' => 'England',
        'er' => 'Eritrea',
        'es' => 'Spain',
        'et' => 'Ethiopia',
        'fi' => 'Finland',
        'fj' => 'Fiji',
        'fk' => 'Falkland Islands',
        'fm' => 'Micronesia',
        'fo' => 'Faroe Islands',
        'fr' => 'France',
        'ga' => 'Gabon',
        'gb' => 'United Kingdom',
        'gd' => 'Grenada',
        'ge' => 'Georgia',
        'gh' => 'Ghana',
        'gi' => 'Gibraltar',
        'gl' => 'Greenland',
        'gm' => 'Gambia',
        'gn' => 'Guinea',
        'gp' => 'Guadeloupe',
        'gq' => 'Equatorial Guinea',
        'gr' => 'Greece',
        'gs' => 'South Georgia and the South Sandwich Islands',
        'gt' => 'Guatemala',
        'gu' => 'Guam',
        'gw' => 'Guinea-Bissau',
        'gy' => 'Guyana',
        'hk' => 'Hong Kong',
        'hm' => 'Heard Island and McDonald Islands',
        'hn' => 'Honduras',
        'hr' => 'Croatia',
        'ht' => 'Haiti',
        'hu' => 'Hungary',
        'id' => 'Indonesia',
        'ie' => 'Republic of Ireland',
        'il' => 'Israel',
        'in' => 'India',
        'io' => 'British Indian Ocean Territory',
        'iq' => 'Iraq',
        'ir' => 'Iran',
        'is' => 'Iceland',
        'it' => 'Italy',
        'jm' => 'Jamaica',
        'jo' => 'Jordan',
        'jp' => 'Japan',
        'ke' => 'Kenya',
        'kg' => 'Kyrgyzstan',
        'kh' => 'Cambodia',
        'ki' => 'Kiribati',
        'km' => 'Comoros',
        'kn' => 'Saint Kitts and Nevis',
        'kp' => 'North Korea',
        'kr' => 'South Korea',
        'kw' => 'Kuwait',
        'ky' => 'Cayman Islands',
        'kz' => 'Kazakhstan',
        'la' => 'Laos',
        'lb' => 'Lebanon',
        'lc' => 'Saint Lucia',
        'li' => 'Liechtenstein',
        'lk' => 'Sri Lanka',
        'lr' => 'Liberia',
        'ls' => 'Lesotho',
        'lt' => 'Lithuania',
        'lu' => 'Luxembourg',
        'lv' => 'Latvia',
        'ly' => 'Libya',
        'ma' => 'Morocco',
        'mc' => 'Monaco',
        'md' => 'Moldova',
        'me' => 'Montenegro',
        'mg' => 'Madagascar',
        'mh' => 'Marshall Islands',
        'mk' => 'Macedonia',
        'ml' => 'Mali',
        'mm' => 'Myanmar',
        'mn' => 'Mongolia',
        'mo' => 'Macao',
        'mp' => 'Northern Mariana Islands',
        'mq' => 'Martinique',
        'mr' => 'Mauritania',
        'ms' => 'Montserrat',
        'mt' => 'Malta',
        'mu' => 'Mauritius',
        'mv' => 'Maldives',
        'mw' => 'Malawi',
        'mx' => 'Mexico',
        'my' => 'Malaysia',
        'mz' => 'Mozambique',
        'na' => 'Namibia',
        'nc' => 'New Caledonia',
        'ne' => 'Niger',
        'nf' => 'Norfolk Island',
        'ng' => 'Nigeria',
        'ni' => 'Nicaragua',
        'nl' => 'Netherlands',
        'no' => 'Norway',
        'np' => 'Nepal',
        'nr' => 'Nauru',
        'nu' => 'Niue',
        'nz' => 'New Zealand',
        'om' => 'Oman',
        'pa' => 'Panama',
        'pe' => 'Peru',
        'pf' => 'French Polynesia',
        'pg' => 'Papua New Guinea',
        'ph' => 'Philippines',
        'pk' => 'Pakistan',
        'pl' => 'Poland',
        'pm' => 'Saint Pierre and Miquelon',
        'pn' => 'Pitcairn',
        'pr' => 'Puerto Rico',
        'ps' => 'Palestinian Territory',
        'pt' => 'Portugal',
        'pw' => 'Belau',
        'py' => 'Paraguay',
        'qa' => 'Qatar',
        'ro' => 'Romania',
        'rs' => 'Serbia',
        'ru' => 'Russia',
        'rw' => 'Rwanda',
        'sa' => 'Saudi Arabia',
        'sb' => 'Solomon Islands',
        'sc' => 'Seychelles',
        'gb-sct' => 'Scotland',
        'sd' => 'Sudan',
        'se' => 'Sweden',
        'sg' => 'Singapore',
        'sh' => 'Saint Helena',
        'si' => 'Slovenia',
        'sk' => 'Slovakia',
        'sl' => 'Sierra Leone',
        'sm' => 'San Marino',
        'sn' => 'Senegal',
        'so' => 'Somalia',
        'sr' => 'Suriname',
        'ss' => 'South Sudan',
        'st' => 'São Tomé and Príncipe',
        'sv' => 'El Salvador',
        'sy' => 'Syria',
        'sz' => 'Swaziland',
        'tc' => 'Turks and Caicos Islands',
        'td' => 'Chad',
        'tf' => 'French Southern Territories',
        'tg' => 'Togo',
        'th' => 'Thailand',
        'tj' => 'Tajikistan',
        'tk' => 'Tokelau',
        'tl' => 'Timor-Leste',
        'tm' => 'Turkmenistan',
        'tn' => 'Tunisia',
        'to' => 'Tonga',
        'tr' => 'Turkey',
        'tt' => 'Trinidad and Tobago',
        'tv' => 'Tuvalu',
        'tw' => 'Taiwan',
        'tz' => 'Tanzania',
        'ua' => 'Ukraine',
        'ug' => 'Uganda',
        'us' => 'United States',
        'uy' => 'Uruguay',
        'uz' => 'Uzbekistan',
        'va' => 'Vatican',
        'vc' => 'Saint Vincent and the Grenadines',
        've' => 'Venezuela',
        'vg' => 'British Virgin Islands',
        'vi' => 'United States Virgin Islands',
        'vn' => 'Vietnam',
        'vu' => 'Vanuatu',
        'gb-wls' => 'Wales',
        'wf' => 'Wallis and Futuna',
        'ws' => 'Western Samoa',
        'ye' => 'Yemen',
        'yt' => 'Mayotte',
        'za' => 'South Africa',
        'zm' => 'Zambia',
        'zw' => 'Zimbabwe',
    ],

    'locales' => [
        'af' => [
            'locale' => 'af',
            'code' => 'af',
            'name' => 'Afrikaans',
            'dir' => 'ltr',
            'flag' => 'za',
        ],
        'am' => [
            'locale' => 'am',
            'code' => 'am',
            'name' => 'አማርኛ',
            'dir' => 'ltr',
            'flag' => 'et',
        ],
        'ar' => [
            'locale' => 'ar',
            'code' => 'ar',
            'name' => 'العربية',
            'dir' => 'rtl',
            'flag' => 'ar',
        ],
        'ary' => [
            'locale' => 'ar',
            'code' => 'ary',
            'name' => 'العربية المغربية',
            'dir' => 'rtl',
            'flag' => 'ma',
        ],
        'az' => [
            'locale' => 'az',
            'code' => 'az',
            'name' => 'Azərbaycan',
            'dir' => 'ltr',
            'flag' => 'az',
        ],
        'azb' => [
            'locale' => 'az',
            'code' => 'azb',
            'name' => 'گؤنئی آذربایجان',
            'dir' => 'rtl',
            'flag' => 'az',
        ],
        'bel' => [
            'locale' => 'be',
            'code' => 'bel',
            'name' => 'Беларуская мова',
            'dir' => 'ltr',
            'flag' => 'by',
        ],
        'bg_BG' => [
            'locale' => 'bg',
            'code' => 'bg_BG',
            'name' => 'български',
            'dir' => 'ltr',
            'flag' => 'bg',
        ],
        'bn_BD' => [
            'locale' => 'bn',
            'code' => 'bn_BD',
            'name' => 'বাংলা',
            'dir' => 'ltr',
            'flag' => 'bd',
        ],
        'bo' => [
            'locale' => 'bo',
            'code' => 'bo',
            'name' => 'བོད་སྐད',
            'dir' => 'ltr',
            'flag' => 'tibet',
        ],
        'bs_BA' => [
            'locale' => 'bs',
            'code' => 'bs_BA',
            'name' => 'Bosanski',
            'dir' => 'ltr',
            'flag' => 'ba',
        ],
        'ca' => [
            'locale' => 'ca',
            'code' => 'ca_ES',
            'name' => 'Catalan',
            'dir' => 'ltr',
            'flag' => 'es',
        ],
        'ceb' => [
            'locale' => 'ceb',
            'code' => 'ceb',
            'name' => 'Cebuano',
            'dir' => 'ltr',
            'flag' => 'ph',
        ],
        'cs_CZ' => [
            'locale' => 'cs',
            'code' => 'cs_CZ',
            'name' => 'Čeština',
            'dir' => 'ltr',
            'flag' => 'cz',
        ],
        'cy' => [
            'locale' => 'cy',
            'code' => 'cy',
            'name' => 'Cymraeg',
            'dir' => 'ltr',
            'flag' => 'gb-wls',
        ],
        'da_DK' => [
            'locale' => 'da',
            'code' => 'da_DK',
            'name' => 'Dansk',
            'dir' => 'ltr',
            'flag' => 'dk',
        ],
        'de_CH' => [
            'locale' => 'de',
            'code' => 'de_CH',
            'name' => 'Deutsch',
            'dir' => 'ltr',
            'flag' => 'ch',
        ],
        'de_CH_informal' => [
            'locale' => 'de',
            'code' => 'de_CH_informal',
            'name' => 'Deutsch',
            'dir' => 'ltr',
            'flag' => 'ch',
        ],
        'de_DE' => [
            'locale' => 'de',
            'code' => 'de_DE',
            'name' => 'Deutsch',
            'dir' => 'ltr',
            'flag' => 'de',
        ],
        'de_DE_formal' => [
            'locale' => 'de',
            'code' => 'de_DE_formal',
            'name' => 'Deutsch',
            'dir' => 'ltr',
            'flag' => 'de',
        ],
        'el' => [
            'locale' => 'el',
            'code' => 'el',
            'name' => 'Ελληνικά',
            'dir' => 'ltr',
            'flag' => 'gr',
        ],
        'en_US' => [
            'locale' => 'en',
            'code' => 'en_US',
            'name' => 'English',
            'dir' => 'ltr',
            'flag' => 'us',
        ],
        'en_AU' => [
            'locale' => 'en',
            'code' => 'en_AU',
            'name' => 'English',
            'dir' => 'ltr',
            'flag' => 'au',
        ],
        'en_CA' => [
            'locale' => 'en',
            'code' => 'en_CA',
            'name' => 'English',
            'dir' => 'ltr',
            'flag' => 'ca',
        ],
        'en_GB' => [
            'locale' => 'en',
            'code' => 'en_GB',
            'name' => 'English',
            'dir' => 'ltr',
            'flag' => 'gb',
        ],
        'en_NZ' => [
            'locale' => 'en',
            'code' => 'en_NZ',
            'name' => 'English',
            'dir' => 'ltr',
            'flag' => 'nz',
        ],
        'en_ZA' => [
            'locale' => 'en',
            'code' => 'en_ZA',
            'name' => 'English',
            'dir' => 'ltr',
            'flag' => 'za',
        ],
        'es_AR' => [
            'locale' => 'es',
            'code' => 'es_AR',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 'ar',
        ],
        'es_CL' => [
            'locale' => 'es',
            'code' => 'es_CL',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 'cl',
        ],
        'es_CO' => [
            'locale' => 'es',
            'code' => 'es_CO',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 'co',
        ],
        'es_ES' => [
            'locale' => 'es',
            'code' => 'es_ES',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 'es',
        ],
        'es_GT' => [
            'locale' => 'es',
            'code' => 'es_GT',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 'gt',
        ],
        'es_MX' => [
            'locale' => 'es',
            'code' => 'es_MX',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 'mx',
        ],
        'es_PE' => [
            'locale' => 'es',
            'code' => 'es_PE',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 'pe',
        ],
        'es_VE' => [
            'locale' => 'es',
            'code' => 'es_VE',
            'name' => 'Español',
            'dir' => 'ltr',
            'flag' => 've',
        ],
        'et' => [
            'locale' => 'et',
            'code' => 'et',
            'name' => 'Eesti',
            'dir' => 'ltr',
            'flag' => 'ee',
        ],
        'eu' => [
            'locale' => 'eu',
            'code' => 'eu',
            'name' => 'Euskara',
            'dir' => 'ltr',
            'flag' => 'fr',
        ],
        'fa_AF' => [
            'locale' => 'fa',
            'code' => 'fa_AF',
            'name' => 'فارسی',
            'dir' => 'rtl',
            'flag' => 'af',
        ],
        'fa_IR' => [
            'locale' => 'fa',
            'code' => 'fa_IR',
            'name' => 'فارسی',
            'dir' => 'rtl',
            'flag' => 'ir',
        ],
        'fi' => [
            'locale' => 'fi',
            'code' => 'fi',
            'name' => 'Suomi',
            'dir' => 'ltr',
            'flag' => 'fi',
        ],
        'fo' => [
            'locale' => 'fo',
            'code' => 'fo',
            'name' => 'Føroyskt',
            'dir' => 'ltr',
            'flag' => 'fo',
        ],
        'fr_BE' => [
            'locale' => 'fr',
            'code' => 'fr_BE',
            'name' => 'Français',
            'dir' => 'ltr',
            'flag' => 'be',
        ],
        'fr_FR' => [
            'locale' => 'fr',
            'code' => 'fr_FR',
            'name' => 'Français',
            'dir' => 'ltr',
            'flag' => 'fr',
        ],
        'fy' => [
            'locale' => 'fy',
            'code' => 'fy',
            'name' => 'Frysk',
            'dir' => 'ltr',
            'flag' => 'nl',
        ],
        'gd' => [
            'locale' => 'gd',
            'code' => 'gd',
            'name' => 'Gàidhlig',
            'dir' => 'ltr',
            'flag' => 'gb-sct',
        ],
        'gl_ES' => [
            'locale' => 'gl',
            'code' => 'gl_ES',
            'name' => 'Galego',
            'dir' => 'ltr',
            'flag' => 'gl',
        ],
        'gu' => [
            'locale' => 'gu',
            'code' => 'gu',
            'name' => 'ગુજરાતી',
            'dir' => 'ltr',
            'flag' => 'in',
        ],
        'haz' => [
            'locale' => 'haz',
            'code' => 'haz',
            'name' => 'هزاره گی',
            'dir' => 'rtl',
            'flag' => 'af',
        ],
        'he_IL' => [
            'locale' => 'he',
            'code' => 'he_IL',
            'name' => 'עברית',
            'dir' => 'rtl',
            'flag' => 'il',
        ],
        'hi_IN' => [
            'locale' => 'hi',
            'code' => 'hi_IN',
            'name' => 'हिन्दी',
            'dir' => 'ltr',
            'flag' => 'in',
        ],
        'hr' => [
            'locale' => 'hr',
            'code' => 'hr',
            'name' => 'Hrvatski',
            'dir' => 'ltr',
            'flag' => 'hr',
        ],
        'ht' => [
            'locale' => 'ht',
            'code' => 'ht',
            'name' => 'Kreyòl Ayisyen',
            'dir' => 'ltr',
            'flag' => 'ht',
        ],
        'hu_HU' => [
            'locale' => 'hu',
            'code' => 'hu_HU',
            'name' => 'Magyar',
            'dir' => 'ltr',
            'flag' => 'hu',
        ],
        'hy' => [
            'locale' => 'hy',
            'code' => 'hy',
            'name' => 'Հայերեն',
            'dir' => 'ltr',
            'flag' => 'am',
        ],
        'id_ID' => [
            'locale' => 'id',
            'code' => 'id_ID',
            'name' => 'Bahasa Indonesia',
            'dir' => 'ltr',
            'flag' => 'id',
        ],
        'is_IS' => [
            'locale' => 'is',
            'code' => 'is_IS',
            'name' => 'Íslenska',
            'dir' => 'ltr',
            'flag' => 'is',
        ],
        'it_IT' => [
            'locale' => 'it',
            'code' => 'it_IT',
            'name' => 'Italiano',
            'dir' => 'ltr',
            'flag' => 'it',
        ],
        'ja' => [
            'locale' => 'ja',
            'code' => 'ja',
            'name' => '日本語',
            'dir' => 'ltr',
            'flag' => 'jp',
        ],
        'jv_ID' => [
            'locale' => 'jv',
            'code' => 'jv_ID',
            'name' => 'Basa Jawa',
            'dir' => 'ltr',
            'flag' => 'id',
        ],
        'ka_GE' => [
            'locale' => 'ka',
            'code' => 'ka_GE',
            'name' => 'ქართული',
            'dir' => 'ltr',
            'flag' => 'ge',
        ],
        'kk' => [
            'locale' => 'kk',
            'code' => 'kk',
            'name' => 'Қазақ тілі',
            'dir' => 'ltr',
            'flag' => 'kz',
        ],
        'kh' => [
            'locale' => 'kh',
            'code' => 'kh',
            'name' => 'Cambodia',
            'dir' => 'ltr',
            'flag' => 'kh',
        ],
        'ko_KR' => [
            'locale' => 'ko',
            'code' => 'ko_KR',
            'name' => '한국어',
            'dir' => 'ltr',
            'flag' => 'kr',
        ],
        'ky_KG' => [
            'locale' => 'ky',
            'code' => 'ky_KG',
            'name' => 'Кыргызча',
            'dir' => 'ltr',
            'flag' => 'kg',
        ],
        'ckb' => [
            'locale' => 'ku',
            'code' => 'ckb',
            'name' => 'کوردی',
            'dir' => 'rtl',
            'flag' => 'kurdistan',
        ],
        'lo' => [
            'locale' => 'lo',
            'code' => 'lo',
            'name' => 'ພາສາລາວ',
            'dir' => 'ltr',
            'flag' => 'la',
        ],
        'lt_LT' => [
            'locale' => 'lt',
            'code' => 'lt_LT',
            'name' => 'Lietuviškai',
            'dir' => 'ltr',
            'flag' => 'lt',
        ],
        'lv' => [
            'locale' => 'lv',
            'code' => 'lv',
            'name' => 'Latviešu valoda',
            'dir' => 'ltr',
            'flag' => 'lv',
        ],
        'mk_MK' => [
            'locale' => 'mk',
            'code' => 'mk_MK',
            'name' => 'македонски јазик',
            'dir' => 'ltr',
            'flag' => 'mk',
        ],
        'mn' => [
            'locale' => 'mn',
            'code' => 'mn',
            'name' => 'Монгол хэл',
            'dir' => 'ltr',
            'flag' => 'mn',
        ],
        'mr' => [
            'locale' => 'mr',
            'code' => 'mr',
            'name' => 'मराठी',
            'dir' => 'ltr',
            'flag' => 'in',
        ],
        'ms_MY' => [
            'locale' => 'ms',
            'code' => 'ms_MY',
            'name' => 'Bahasa Melayu',
            'dir' => 'ltr',
            'flag' => 'my',
        ],
        'my_MM' => [
            'locale' => 'my',
            'code' => 'my_MM',
            'name' => 'ဗမာစာ',
            'dir' => 'ltr',
            'flag' => 'mm',
        ],
        'mv' => [
            'locale' => 'mv',
            'code' => 'mv',
            'name' => 'Maldives',
            'dir' => 'rtl',
            'flag' => 'mv',
        ],
        'nb_NO' => [
            'locale' => 'nb',
            'code' => 'nb_NO',
            'name' => 'Norsk Bokmål',
            'dir' => 'ltr',
            'flag' => 'no',
        ],
        'ne_NP' => [
            'locale' => 'ne',
            'code' => 'ne_NP',
            'name' => 'नेपाली',
            'dir' => 'ltr',
            'flag' => 'np',
        ],
        'nl_NL' => [
            'locale' => 'nl',
            'code' => 'nl_NL',
            'name' => 'Nederlands',
            'dir' => 'ltr',
            'flag' => 'nl',
        ],
        'nl_NL_formal' => [
            'locale' => 'nl',
            'code' => 'nl_NL_formal',
            'name' => 'Nederlands',
            'dir' => 'ltr',
            'flag' => 'nl',
        ],
        'nn_NO' => [
            'locale' => 'nn',
            'code' => 'nn_NO',
            'name' => 'Norsk Nynorsk',
            'dir' => 'ltr',
            'flag' => 'no',
        ],
        'pl_PL' => [
            'locale' => 'pl',
            'code' => 'pl_PL',
            'name' => 'Polski',
            'dir' => 'ltr',
            'flag' => 'pl',
        ],
        'ps' => [
            'locale' => 'ps',
            'code' => 'ps',
            'name' => 'پښتو',
            'dir' => 'rtl',
            'flag' => 'af',
        ],
        'pt_BR' => [
            'locale' => 'pt',
            'code' => 'pt_BR',
            'name' => 'Português',
            'dir' => 'ltr',
            'flag' => 'br',
        ],
        'pt_PT' => [
            'locale' => 'pt',
            'code' => 'pt_PT',
            'name' => 'Português',
            'dir' => 'ltr',
            'flag' => 'pt',
        ],
        'ro_RO' => [
            'locale' => 'ro',
            'code' => 'ro_RO',
            'name' => 'Română',
            'dir' => 'ltr',
            'flag' => 'ro',
        ],
        'ru_RU' => [
            'locale' => 'ru',
            'code' => 'ru_RU',
            'name' => 'Русский',
            'dir' => 'ltr',
            'flag' => 'ru',
        ],
        'si_LK' => [
            'locale' => 'si',
            'code' => 'si_LK',
            'name' => 'සිංහල',
            'dir' => 'ltr',
            'flag' => 'lk',
        ],
        'sk_SK' => [
            'locale' => 'sk',
            'code' => 'sk_SK',
            'name' => 'Slovenčina',
            'dir' => 'ltr',
            'flag' => 'sk',
        ],
        'sl_SI' => [
            'locale' => 'sl',
            'code' => 'sl_SI',
            'name' => 'Slovenščina',
            'dir' => 'ltr',
            'flag' => 'si',
        ],
        'so_SO' => [
            'locale' => 'so',
            'code' => 'so_SO',
            'name' => 'Af-Soomaali',
            'dir' => 'ltr',
            'flag' => 'so',
        ],
        'sq' => [
            'locale' => 'sq',
            'code' => 'sq',
            'name' => 'Shqip',
            'dir' => 'ltr',
            'flag' => 'al',
        ],
        'sq_AL' => [
            'locale' => 'sq',
            'code' => 'sq_AL',
            'name' => 'Shqip (Shqipëri)',
            'dir' => 'ltr',
            'flag' => 'al',
        ],
        'sr_RS' => [
            'locale' => 'sr',
            'code' => 'sr_RS',
            'name' => 'Српски језик',
            'dir' => 'ltr',
            'flag' => 'rs',
        ],
        'su_ID' => [
            'locale' => 'su',
            'code' => 'su_ID',
            'name' => 'Basa Sunda',
            'dir' => 'ltr',
            'flag' => 'id',
        ],
        'sv_SE' => [
            'locale' => 'sv',
            'code' => 'sv_SE',
            'name' => 'Svenska',
            'dir' => 'ltr',
            'flag' => 'se',
        ],
        'szl' => [
            'locale' => 'szl',
            'code' => 'szl',
            'name' => 'Ślōnskŏ gŏdka',
            'dir' => 'ltr',
            'flag' => 'pl',
        ],
        'sw' => [
            'locale' => 'sw',
            'code' => 'sw',
            'name' => 'Swahili',
            'dir' => 'ltr',
            'flag' => 'tz',
        ],
        'ta_LK' => [
            'locale' => 'ta',
            'code' => 'ta_LK',
            'name' => 'தமிழ்',
            'dir' => 'ltr',
            'flag' => 'lk',
        ],
        'th' => [
            'locale' => 'th',
            'code' => 'th',
            'name' => 'ไทย',
            'dir' => 'ltr',
            'flag' => 'th',
        ],
        'ti' => [
            'locale' => 'ti',
            'code' => 'ti',
            'name' => 'ትግርኛ',
            'dir' => 'ltr',
            'flag' => 'er',
        ],
        'tl' => [
            'locale' => 'tl',
            'code' => 'tl',
            'name' => 'Tagalog',
            'dir' => 'ltr',
            'flag' => 'ph',
        ],
        'tr_TR' => [
            'locale' => 'tr',
            'code' => 'tr_TR',
            'name' => 'Türkçe',
            'dir' => 'ltr',
            'flag' => 'tr',
        ],
        'ug_CN' => [
            'locale' => 'ug',
            'code' => 'ug_CN',
            'name' => 'Uyƣurqə',
            'dir' => 'ltr',
            'flag' => 'cn',
        ],
        'uk' => [
            'locale' => 'uk',
            'code' => 'uk',
            'name' => 'Українська',
            'dir' => 'ltr',
            'flag' => 'ua',
        ],
        'ur' => [
            'locale' => 'ur',
            'code' => 'ur',
            'name' => 'اردو',
            'dir' => 'rtl',
            'flag' => 'pk',
        ],
        'uz_UZ' => [
            'locale' => 'uz',
            'code' => 'uz_UZ',
            'name' => 'Oʻzbek',
            'dir' => 'ltr',
            'flag' => 'uz',
        ],
        'vi' => [
            'locale' => 'vi',
            'code' => 'vi',
            'name' => 'Tiếng Việt',
            'dir' => 'ltr',
            'flag' => 'vn',
        ],
        'zh_CN' => [
            'locale' => 'zh',
            'code' => 'zh_CN',
            'name' => '中文 (中国)',
            'dir' => 'ltr',
            'flag' => 'cn',
        ],
        'zh_HK' => [
            'locale' => 'zh',
            'code' => 'zh_HK',
            'name' => '中文 (香港)',
            'dir' => 'ltr',
            'flag' => 'hk',
        ],
        'zh_TW' => [
            'locale' => 'zh',
            'code' => 'zh_TW',
            'name' => '中文 (台灣)',
            'dir' => 'ltr',
            'flag' => 'tw',
        ],
        'tg' => [
            'locale' => 'tg',
            'code' => 'tg',
            'name' => 'Tajik',
            'dir' => 'ltr',
            'flag' => 'tj',
        ],
    ],
];
