<?php

namespace App\Containers\AppSection\Shift\Jobs;

use App\Containers\AppSection\Production\Enums\HourlyRecordStatus;
use App\Containers\AppSection\Production\Models\HourlyRecord;
use App\Containers\AppSection\Shift\Models\Shift;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Carbon;

/**
 * Scheduled Job — runs at :00 of every hour.
 *
 * Lifecycle transitions for hourly_records of active shifts today:
 *   pending   → active    (when current hour >= slot start hour)
 *   active    → completed (when current hour >= slot end hour)
 *
 * Does NOT create new records — only transitions status.
 * Skeleton records are pre-generated by CreateShift / UpdateShift.
 */
final class ActivateHourlyRecordsJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public function handle(): void
    {
        $now         = Carbon::now();
        $currentHour = (int) $now->format('G'); // 0–23

        // Active shifts for today
        $shiftIds = Shift::where('is_active', true)
            ->where('date', $now->toDateString())
            ->pluck('id');

        if ($shiftIds->isEmpty()) {
            return;
        }

        // ── 1. Complete records whose slot has ended ──
        // Must run BEFORE activation so a slot ending at the current hour
        // gets completed before the next slot is activated.
        $toComplete = HourlyRecord::whereIn('shift_id', $shiftIds)
            ->where('status', HourlyRecordStatus::Active->value)
            ->get()
            ->filter(function (HourlyRecord $record) use ($currentHour) {
                // hour_slot = "7h-8h" → end = 8
                $endHour = (int) explode('h', explode('-', $record->hour_slot)[1])[0];

                return $endHour <= $currentHour;
            })
            ->pluck('id');

        if ($toComplete->isNotEmpty()) {
            HourlyRecord::whereIn('id', $toComplete)
                ->update(['status' => HourlyRecordStatus::Completed->value]);
        }

        // ── 2. Activate records whose slot has started ──
        $toActivate = HourlyRecord::whereIn('shift_id', $shiftIds)
            ->where('status', HourlyRecordStatus::Pending->value)
            ->get()
            ->filter(function (HourlyRecord $record) use ($currentHour) {
                // hour_slot = "7h-8h" → start = 7
                $startHour = (int) explode('h', $record->hour_slot)[0];

                return $startHour <= $currentHour;
            })
            ->pluck('id');

        if ($toActivate->isNotEmpty()) {
            HourlyRecord::whereIn('id', $toActivate)
                ->update(['status' => HourlyRecordStatus::Active->value]);
        }
    }
}
