<?php

namespace App\Containers\AppSection\Shift\Tests\Unit;

use App\Containers\AppSection\Department\Enums\ProductivityType;
use App\Containers\AppSection\Department\Models\Department;
use App\Containers\AppSection\Production\Models\HourlyRecord;
use App\Containers\AppSection\Production\Models\ProductionLine;
use App\Containers\AppSection\Shift\Models\Shift;
use App\Containers\AppSection\Shift\Models\ShiftDetail;
use App\Containers\AppSection\Shift\Tasks\GenerateHourlyRecordsTask;
use App\Containers\AppSection\Shift\Tasks\SyncHourlyRecordsTask;
use App\Containers\AppSection\Shift\Tests\UnitTestCase;

/**
 * Unit tests for SyncHourlyRecordsTask — aligned slot generation.
 *
 * Verifies that SyncHourlyRecordsTask produces identical slots to
 * GenerateHourlyRecordsTask, including partial first/last slots,
 * correct kpi_hours/kpi_minutes/kpi_percent, and preserves actual data.
 */
final class SyncHourlyRecordsTaskTest extends UnitTestCase
{
    private ProductionLine $line;
    private Department $dept;

    protected function setUp(): void
    {
        parent::setUp();

        $this->line = ProductionLine::create([
            'code' => 'fls', 'label' => 'FLS', 'color' => '#3b82f6',
            'sort_order' => 1, 'is_active' => true,
        ]);

        $this->dept = Department::create([
            'production_line_id' => $this->line->id,
            'code' => 'print', 'label' => 'Print', 'label_en' => 'Print',
            'icon' => 'Printer', 'unit' => 'file', 'sort_order' => 1, 'is_active' => true,
            'kpi_per_hour' => 100,
            'productivity_type' => ProductivityType::PerPerson->value,
        ]);
    }

    // ── Helpers ──────────────────────────────────────────

    private function createShiftWithDetail(string $startTime = '06:30:00', float $workHours = 8): Shift
    {
        $shift = Shift::create([
            'date' => '2026-04-10',
            'shift_number' => 1,
            'start_time' => '06:00',
            'end_time' => '15:00',
            'is_active' => true,
        ]);

        ShiftDetail::create([
            'shift_id'           => $shift->id,
            'department_id'      => $this->dept->id,
            'shift_number'       => 1,
            'headcount'          => 5,
            'start_time'         => $startTime,
            'work_hours'         => $workHours,
            'prep_minutes'       => 0,
            'break1_start'       => null,
            'break1_minutes'     => 0,
            'meal_break_start'   => '11:00',
            'meal_break_minutes' => 30,
            'break2_start'       => null,
            'break2_minutes'     => 0,
            'break3_start'       => null,
            'break3_minutes'     => 0,
        ]);

        return $shift;
    }

    // ── Tests ────────────────────────────────────────────

    /**
     * Partial-hour dept: sync must preserve all slots generated by Generate.
     *
     * print starts at 06:30, work_hours=8, meal=30min → total span = 8h30.
     * GenerateHourlyRecordsTask produces 9 aligned slots (index 0–8).
     * SyncHourlyRecordsTask must produce the exact same 9 slots.
     */
    public function testSyncPreservesAllSlotsIncludingPartialHours(): void
    {
        $shift = $this->createShiftWithDetail('06:30:00', 8);

        // Step 1: Generate initial records
        app(GenerateHourlyRecordsTask::class)->run($shift);
        $generatedCount = HourlyRecord::where('shift_id', $shift->id)->count();
        $this->assertSame(9, $generatedCount, 'Generate should create 9 aligned slots for 06:30 + 8h work + 30min break');

        // Step 2: Run sync — should produce identical slot count
        app(SyncHourlyRecordsTask::class)->run($shift);

        $afterSync = HourlyRecord::where('shift_id', $shift->id)->count();
        $this->assertSame(9, $afterSync, 'Sync must preserve all 9 slots (including partial first/last)');

        // Verify no records were soft-deleted
        $softDeleted = HourlyRecord::onlyTrashed()->where('shift_id', $shift->id)->count();
        $this->assertSame(0, $softDeleted, 'No slots should be soft-deleted after sync');
    }

    /**
     * Verify kpi_hours/kpi_minutes/kpi_percent are synced correctly.
     */
    public function testSyncUpdatesKpiFieldsCorrectly(): void
    {
        $shift = $this->createShiftWithDetail('06:30:00', 8);

        app(GenerateHourlyRecordsTask::class)->run($shift);
        $generated = HourlyRecord::where('shift_id', $shift->id)
            ->orderBy('hour_index')
            ->get(['hour_index', 'kpi_hours', 'kpi_minutes', 'kpi_percent', 'target']);

        // Run sync
        app(SyncHourlyRecordsTask::class)->run($shift);
        $synced = HourlyRecord::where('shift_id', $shift->id)
            ->orderBy('hour_index')
            ->get(['hour_index', 'kpi_hours', 'kpi_minutes', 'kpi_percent', 'target']);

        // Compare each slot
        foreach ($generated as $i => $gen) {
            $syn = $synced[$i];
            $this->assertSame((float) $gen->kpi_hours, (float) $syn->kpi_hours, "Slot {$i}: kpi_hours mismatch");
            $this->assertSame($gen->kpi_minutes, $syn->kpi_minutes, "Slot {$i}: kpi_minutes mismatch");
            $this->assertSame((float) $gen->kpi_percent, (float) $syn->kpi_percent, "Slot {$i}: kpi_percent mismatch");
            $this->assertSame($gen->target, $syn->target, "Slot {$i}: target mismatch");
        }
    }

    /**
     * Verify actual data is preserved during sync.
     */
    public function testSyncPreservesActualData(): void
    {
        $shift = $this->createShiftWithDetail('06:00:00', 8);

        app(GenerateHourlyRecordsTask::class)->run($shift);

        // Simulate production data on first record
        $first = HourlyRecord::where('shift_id', $shift->id)
            ->where('hour_index', 0)
            ->first();
        $first->update([
            'actual'               => 450,
            'hour_start_inventory' => 1200,
            'efficiency'           => 90.0,
        ]);

        // Run sync
        app(SyncHourlyRecordsTask::class)->run($shift);

        // Verify actual data preserved
        $refreshed = HourlyRecord::find($first->id);
        $this->assertSame(450, $refreshed->actual);
        $this->assertSame(1200, $refreshed->hour_start_inventory);
        $this->assertEquals(90.0, (float) $refreshed->efficiency);
    }

    /**
     * Full-hour dept (start on the hour): sync should work identically to generate.
     */
    public function testSyncWorksForFullHourDepartment(): void
    {
        $shift = $this->createShiftWithDetail('06:00:00', 8);

        app(GenerateHourlyRecordsTask::class)->run($shift);
        $generatedCount = HourlyRecord::where('shift_id', $shift->id)->count();

        app(SyncHourlyRecordsTask::class)->run($shift);
        $syncedCount = HourlyRecord::where('shift_id', $shift->id)->count();

        $this->assertSame($generatedCount, $syncedCount, 'Full-hour dept: sync count must match generate count');

        $softDeleted = HourlyRecord::onlyTrashed()->where('shift_id', $shift->id)->count();
        $this->assertSame(0, $softDeleted, 'No slots should be soft-deleted');
    }
}
